### ISSUE TITLE
ReferenceError: primordials is not defined

### ISSUE THREAD

**Issue by jamajama1** [Harrup/Craigslist-clone#1]
when I run npm run watch, I get the following errors. I can't track where this error occurs, I've followed the error location and can't find any mention of primordials. I have no clue how to fix this issue, any help would be great. Thanks. 

 CodingPhase-StarterKit@1.0.0 watch /Users/jay/Desktop/Craigslist-clone
 gulp

fs.js:35
} = primordials;
    ^

ReferenceError: primordials is not defined
    at fs.js:35:5
    at req_ (/Users/jay/Desktop/Craigslist-clone/node_modules/natives/index.js:143:24)
    at Object.req [as require] (/Users/jay/Desktop/Craigslist-clone/node_modules/natives/index.js:55:10)
    at Object.<anonymous> (/Users/jay/Desktop/Craigslist-clone/node_modules/vinyl-fs/node_modules/graceful-fs/fs.js:1:37)
    at Module._compile (internal/modules/cjs/loader.js:1158:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1178:10)
    at Module.load (internal/modules/cjs/loader.js:1002:32)
    at Function.Module._load (internal/modules/cjs/loader.js:901:14)
    at Module.require (internal/modules/cjs/loader.js:1044:19)
    at require (internal/modules/cjs/helpers.js:77:18)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! CodingPhase-StarterKit@1.0.0 watch: `gulp`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the CodingPhase-StarterKit@1.0.0 watch script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/jay/.npm/_logs/2021-07-23T21_00_38_745Z-debug.log

**Comment by GabrielDumbrava** [comment]
I got the same error on a different package and got around it by cleaning the non cache:
`npm cache clean --force`

Then I've installed the exact version of node that was required by the project. Error gone.
